.PHONY: build clean

# Build command to compile the Go project
build:
		go build -o fnoSquareOff.exe ./cmd

# Clean command to remove the built executable on Windows
clean:
		del /F /Q fnoSquareOff.exe

# Run command to execute the binary
run:
		./fnoSquareOff.exe